# Site settings
title: Seth Kranzler
email: sethkranzler@gmail.com
description: > 
  This is the personal site of Seth Kranzler
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://sethkranzler.com" # the base hostname & protocol for your site
twitter_username: polyrhythmic
github_username:  polyrhythmatic

# Build settings
sass:
  style: compressed
  sass_dir: _sass
include: ["_pages"]
kramdown:
  input: GFM
collections:
  projects:
    output: true
exclude: ["node_modules", "package.json", "webpack", "webpack.config.js"]

gems:
    - jekyll-minifier

jekyll-minifier:
  exclude: ["js/bundle.js"]