# Site settings
title: Seth Kranzler
email: sethkranzler@gmail.com
description: > 
  This is the personal site of Seth Kranzler
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://sethkranzler.com" # the base hostname & protocol for your site
twitter_username: polyrhythmic
github_username:  polyrhythmatic

include: ["_pages"]
kramdown:
  input: GFM
collections:
  projects:
    output: true
exclude: ["node_modules", "package.json", "webpack", "webpack.config.js", "postcss.config.js", "clearCache.js", "cloudflareKey.js"]
